#!/usr/bin/env python3
"""Generate src/h_distances.rs: the X-ray and neutron lengths GeoStd gives bonds to
hydrogen, as medians by parent element and parent bond count. Fixed mode uses them for the
hydrogens of residues whose restraints are built from the CCD.

Usage: python3 tools/gen_h_distances.py <chem_data> > src/h_distances.rs
"""
import os
import statistics
import sys
from collections import defaultdict


def tokens(line):
    """CIF tokens of one line: quotes delimit a value only at its start, and close only
    before whitespace (so O5' is one bare value)."""
    out, i, n = [], 0, len(line)
    while i < n:
        if line[i].isspace():
            i += 1
        elif line[i] in '\'"':
            q, j = line[i], i + 1
            while j < n and not (line[j] == q and (j + 1 == n or line[j + 1].isspace())):
                j += 1
            out.append(line[i + 1:j])
            i = j + 1
        else:
            j = i
            while j < n and not line[j].isspace():
                j += 1
            out.append(line[i:j])
            i = j
    return out


def loops(path):
    """The loops of a CIF file as {category: [row dicts]} (enough for GeoStd files)."""
    out = defaultdict(list)
    lines = open(path, encoding='utf-8', errors='replace').read().splitlines()
    i = 0
    while i < len(lines):
        if lines[i].strip() != 'loop_':
            i += 1
            continue
        i += 1
        tags = []
        while i < len(lines) and lines[i].strip().startswith('_'):
            tags.append(lines[i].strip())
            i += 1
        values = []
        while i < len(lines):
            s = lines[i].strip()
            if s == 'loop_' or s.startswith('_') or s.startswith('data_'):
                break
            if s and not s.startswith('#'):
                values.extend(tokens(s))
            i += 1
        if not tags:
            continue
        cat = tags[0].split('.')[0]
        names = [t.split('.', 1)[1] for t in tags]
        for k in range(0, len(values) - len(names) + 1, len(names)):
            out[cat].append(dict(zip(names, values[k:k + len(names)])))
    return out


def main(chem_data):
    geostd = os.path.join(chem_data, 'geostd')
    samples = defaultdict(list)
    for d in sorted(os.listdir(geostd)):
        dd = os.path.join(geostd, d)
        if not os.path.isdir(dd):
            continue
        for f in sorted(os.listdir(dd)):
            if not f.startswith('data_') or '_pH_' in f or '_neutron' in f:
                continue
            cif = loops(os.path.join(dd, f))
            element = {a.get('atom_id'): a.get('type_symbol', '').upper()
                       for a in cif['_chem_comp_atom']}
            degree = defaultdict(int)
            for b in cif['_chem_comp_bond']:
                degree[b.get('atom_id_1')] += 1
                degree[b.get('atom_id_2')] += 1
            for b in cif['_chem_comp_bond']:
                a1, a2 = b.get('atom_id_1'), b.get('atom_id_2')
                e1, e2 = element.get(a1), element.get(a2)
                if (e1 in ('H', 'D')) == (e2 in ('H', 'D')):
                    continue
                parent = a2 if e1 in ('H', 'D') else a1
                try:
                    x, n = float(b['value_dist']), float(b['value_dist_neutron'])
                except (KeyError, ValueError):
                    continue
                samples[(element[parent], degree[parent])].append((x, n))
                samples[(element[parent], 0)].append((x, n))
    print('//! Generated by tools/gen_h_distances.py from GeoStd; do not edit.')
    print('')
    print('/// (parent element, parent bond count or 0 for any, X-ray length, neutron length,')
    print('/// number of GeoStd bonds): median lengths of bonds to hydrogen.')
    print('pub const H_DISTANCES: &[(&str, usize, f64, f64, usize)] = &[')
    for (e, deg), v in sorted(samples.items()):
        if len(v) < 20:
            continue
        x = statistics.median(s[0] for s in v)
        n = statistics.median(s[1] for s in v)
        print('    ("%s", %d, %.3f, %.3f, %d),' % (e, deg, x, n, len(v)))
    print('];')
    print(LOOKUP)


LOOKUP = '''
/// GeoStd's (X-ray, neutron) length for a bond from an atom of `element` with
/// `bonds` bonds to a hydrogen, by bond count where GeoStd has enough examples,
/// else for the element. The neutron length is never below the X-ray one (GeoStd
/// gives placeholder neutron values for some elements).
pub fn lookup(element: &str, bonds: usize) -> Option<(f64, f64)> {
    let find = |b: usize| H_DISTANCES.iter().find(|r| r.0 == element && r.1 == b);
    let r = find(bonds).or_else(|| find(0))?;
    Some((r.2, r.3.max(r.2)))
}'''


if __name__ == '__main__':
    main(sys.argv[1])
