#!/usr/bin/env python
"""Generate src/rdkit_valence.rs: which total bond orders RDKit's SanitizeMol accepts for
each element and formal charge. Run with a Python that has RDKit (the version Reduce2
uses), e.g. reference/env/bin/python tools/gen_rdkit_valence.py > src/rdkit_valence.rs
"""
from __future__ import print_function

import rdkit
from rdkit import Chem, RDLogger

RDLogger.DisableLog('rdApp.*')

CHARGES = range(-6, 7)
MAX_VALENCE = 15


def accepted(z, charge, valence, neighbor):
  mol = Chem.RWMol()
  centre = Chem.Atom(z)
  centre.SetFormalCharge(charge)
  i = mol.AddAtom(centre)
  for _ in range(valence):
    j = mol.AddAtom(Chem.Atom(neighbor))
    mol.AddBond(i, j, Chem.BondType.SINGLE)
  try:
    Chem.SanitizeMol(mol)
    return True
  except Exception:
    return False


table = Chem.GetPeriodicTable()
rows = []
for z in range(1, 119):
  symbol = table.GetElementSymbol(z)
  masks = []
  for charge in CHARGES:
    mask = 0
    for v in range(MAX_VALENCE + 1):
      a = accepted(z, charge, v, 6)
      if a != accepted(z, charge, v, 1):
        raise SystemExit('carbon and hydrogen neighbours disagree for %s %d %d' % (symbol, charge, v))
      if a:
        mask |= 1 << v
    masks.append(mask)
  rows.append((symbol.upper(), masks))

print('//! Generated by tools/gen_rdkit_valence.py from RDKit %s; do not edit.' % rdkit.__version__)
print('')
print('/// Lowest formal charge in [`ACCEPTED`].')
print('pub const MIN_CHARGE: i32 = %d;' % CHARGES[0])
print('')
print('/// Per element (upper-case symbol): for each formal charge from MIN_CHARGE up, a bit')
print('/// mask of the total bond orders (0 to %d) that RDKit\'s SanitizeMol accepts.' % MAX_VALENCE)
print('pub const ACCEPTED: &[(&str, [u16; %d])] = &[' % len(CHARGES))
for symbol, masks in rows:
  print('    ("%s", [%s]),' % (symbol, ', '.join('0x%04x' % m for m in masks)))
print('];')
