"""Generate src/linkdata.rs: glycosidic chiral volume signs and default bond
lengths used by automatic linking (mmtbx.monomer_library.glyco_chiral_values,
bondlength_defaults.qm_defaults)."""
import sys
from mmtbx.monomer_library import glyco_chiral_values, bondlength_defaults

out = []
out.append("//! Generated by tools/gen_linkdata.py from cctbx; do not edit.\n")
out.append("/// `glyco_chiral_values.volumes`: anomeric chiral volume per residue name.")
out.append("pub const GLYCO_VOLUMES: &[(&str, f64)] = &[")
for k in sorted(glyco_chiral_values.volumes):
  out.append('    ("%s", %r),' % (k, float(glyco_chiral_values.volumes[k])))
out.append("];\n")
out.append("/// `bondlength_defaults.qm_defaults` entries for single bonds:")
out.append("/// (element 1, element 2, order or 0 for the order-less key, length).")
out.append("pub const QM_DEFAULTS: &[(&str, &str, u8, f64)] = &[")
for k in sorted(bondlength_defaults.qm_defaults, key=lambda k: tuple(str(x) for x in k)):
  v = bondlength_defaults.qm_defaults[k]
  if v is None: continue
  if len(k) == 3:
    if int(k[2]) != 1: continue
    out.append('    ("%s", "%s", 1, %r),' % (k[0], k[1], float(v)))
  elif len(k) == 2:
    out.append('    ("%s", "%s", 0, %r),' % (k[0], k[1], float(v)))
out.append("];")
open(sys.argv[1], 'w').write("\n".join(out) + "\n")
