"""Generate src/resclass_data.rs from iotbx/pdb/common_residue_names.h and the
modified-residue headers, so residue classification matches iotbx exactly."""
import re, sys, os
src = sys.argv[1]  # path to cctbx_project/iotbx/pdb
out = sys.argv[2]
arrays = {}
for fn in ["common_residue_names.h", "modified_aa_names.h", "modified_rna_dna_names.h"]:
    text = open(os.path.join(src, fn)).read()
    for m in re.finditer(r'static const char\*\s+(\w+)\[\]\s*=\s*\{(.*?)\n\s*0\s*\n?\s*\};', text, re.S):
        name, body = m.group(1), m.group(2)
        body = re.sub(r'//[^\n]*', '', body)
        items = re.findall(r'"((?:[^"\\]|\\.)*)"', body)
        arrays[name] = items
need = ["amino_acid", "d_amino_acid", "modified_amino_acid", "rna_dna", "modified_rna_dna",
        "ccp4_mon_lib_rna_dna", "water", "small_molecule", "common_saccharide", "element"]
with open(out, "w") as f:
    f.write("// @generated by tools/gen_resclass.py from iotbx/pdb/common_residue_names.h; do not edit.\n")
    for n in need:
        items = arrays.get(n, [])
        f.write("pub const %s: &[&str] = &[\n" % n.upper())
        for i in items:
            f.write('    "%s",\n' % i.replace('\\', '\\\\'))
        f.write("];\n")
for n in need:
    print(n, len(arrays.get(n, [])), arrays.get(n, [])[:8])
