"""Generate src/spacegroup_data.rs from cctbx: for every space-group setting
cctbx knows, (1) the rotation parts of its representative symmetry operations
(smx, in cctbx order), used to reproduce cctbx's symmetry-averaged unit cell
exactly, and (2) what crystal.symmetry.as_cif_block writes for it (IT number,
crystal system, H-M and Hall symbols, all operations as x,y,z). Keyed by the
Hermann-Mauguin symbol without spaces (plus ":H", ":R", ":1", ":2")."""
import sys
from cctbx import sgtbx

entries = {}
rot_sets, rot_index = [], {}
infos, info_index = [], {}
for sym in sgtbx.space_group_symbol_iterator():
  hm = sym.hermann_mauguin()
  ext = sym.extension()
  key = hm.replace(' ', '').upper()
  has_ext = ext not in ('', '\0')
  full = key + (':' + ext if has_ext else '')
  try:
    sgi = sgtbx.space_group_info(symbol=hm + ((' :' + ext) if has_ext else ''))
  except Exception:
    continue
  g = sgi.group()
  rots = []
  for m in g.smx():
    r = m.r()
    assert r.den() == 1
    rots.extend(int(x) for x in r.num())
  t = tuple(rots)
  if t not in rot_index:
    rot_index[t] = len(rot_sets)
    rot_sets.append(t)
  st = sgi.type()
  info = (st.hall_symbol(), st.number(), g.crystal_system().lower(), st.lookup_symbol(),
          tuple(s.as_xyz() for s in g))
  if info not in info_index:
    info_index[info] = len(infos)
    infos.append(info)
  for k in (full, key):
    entries.setdefault(k, (rot_index[t], info_index[info]))

out = ["//! Generated by tools/gen_spacegroups.py from cctbx; do not edit.\n"]
out.append("/// Rotation parts (row-major 3x3) of the representative operations of each set.")
out.append("pub const ROT_SETS: &[&[i8]] = &[")
for t in rot_sets:
  out.append("    &[" + ",".join(str(x) for x in t) + "],")
out.append("];\n")
out.append("/// (Hall symbol, IT number, crystal system, H-M symbol, operations).")
out.append("pub const SG_INFO: &[(&str, u16, &str, &str, &[&str])] = &[")
for hall, num, system, lookup, ops in infos:
  out.append('    ("%s", %d, "%s", "%s", &[%s]),' % (hall.replace('"', '\\"'), num, system, lookup,
             ",".join('"%s"' % o for o in ops)))
out.append("];\n")
out.append("/// Symbol (no spaces, upper case, optional :ext) -> (ROT_SETS index, SG_INFO index).")
out.append("pub const SYMBOLS: &[(&str, u16, u16)] = &[")
for k in sorted(entries):
  out.append('    ("%s", %d, %d),' % (k, entries[k][0], entries[k][1]))
out.append("];")
open(sys.argv[1], 'w').write("\n".join(out) + "\n")
print(len(entries), "symbols,", len(rot_sets), "rotation sets,", len(infos), "settings")
