//! Generated by tools/gen_h_distances.py from GeoStd; do not edit.

/// (parent element, parent bond count or 0 for any, X-ray length, neutron length,
/// number of GeoStd bonds): median lengths of bonds to hydrogen.
pub const H_DISTANCES: &[(&str, usize, f64, f64, usize)] = &[
    ("B", 0, 1.188, 1.000, 91),
    ("B", 6, 1.188, 1.000, 70),
    ("C", 0, 0.970, 1.090, 888707),
    ("C", 2, 0.913, 1.066, 280),
    ("C", 3, 0.930, 1.080, 254884),
    ("C", 4, 0.970, 1.090, 633543),
    ("N", 0, 0.860, 1.020, 80591),
    ("N", 2, 0.890, 1.040, 2033),
    ("N", 3, 0.860, 1.020, 77642),
    ("N", 4, 0.890, 1.040, 916),
    ("O", 0, 0.850, 0.980, 36699),
    ("O", 2, 0.850, 0.980, 36686),
    ("P", 0, 1.209, 1.209, 56),
    ("P", 4, 1.209, 1.209, 42),
    ("S", 0, 1.200, 1.200, 745),
    ("S", 2, 1.200, 1.200, 688),
    ("S", 3, 1.200, 1.200, 30),
    ("S", 4, 1.200, 1.200, 27),
    ("SE", 0, 1.444, 1.000, 48),
    ("SE", 2, 1.444, 1.000, 46),
];

/// GeoStd's (X-ray, neutron) length for a bond from an atom of `element` with
/// `bonds` bonds to a hydrogen, by bond count where GeoStd has enough examples,
/// else for the element. The neutron length is never below the X-ray one (GeoStd
/// gives placeholder neutron values for some elements).
pub fn lookup(element: &str, bonds: usize) -> Option<(f64, f64)> {
    let find = |b: usize| H_DISTANCES.iter().find(|r| r.0 == element && r.1 == b);
    let r = find(bonds).or_else(|| find(0))?;
    Some((r.2, r.3.max(r.2)))
}
